# Generated by Django 6.1.1 on 2026-10-02 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceticket",
            name="reported_by",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="assigned_cleaner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"role": "HOUSEKEEPING"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
