# Generated by Django 6.1.1 on 2026-09-30 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestprofile",
            options={
                "verbose_name": "Guest Profile",
                "verbose_name_plural": "Guest Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="guestprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="central_user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="guestprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="guestprofile",
            table="guest_profiles",
        ),
    ]
