# Generated by Django 6.0 on 2026-09-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_platform_admin",
            field=models.BooleanField(
                default=False, help_text="Platform admin with access to all tenants"
            ),
        ),
    ]
