# Generated by Django 6.0 on 2026-09-30 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_verified_user_is_platform_admin"),
        ("guests", "0001_initial"),  # Ensure guests app migration runs first
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestProfile',
        ),
    ]
