# Generated by Django 6.0 on 2026-09-29 11:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9-]+$",
                                "Only lowercase alphanumeric characters and hyphens allowed",
                            )
                        ],
                    ),
                ),
                ("hotel_name", models.CharField(max_length=200)),
                ("db_name", models.CharField(max_length=100, unique=True)),
                ("db_host", models.CharField(default="localhost", max_length=255)),
                ("db_port", models.IntegerField(default=5432)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial Period"),
                            ("ACTIVE", "Active Subscription"),
                            ("SUSPENDED", "Suspended - Payment Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("ARCHIVED", "Archived - Deleted"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField()),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("NPL", "Nepal"),
                            ("IND", "India"),
                            ("BGD", "Bangladesh"),
                            ("LKR", "Sri Lanka"),
                            ("PAK", "Pakistan"),
                            ("BTN", "Bhutan"),
                            ("MDV", "Maldives"),
                            ("AFG", "Afghanistan"),
                        ],
                        max_length=3,
                    ),
                ),
                ("primary_currency", models.CharField(default="NPR", max_length=3)),
                ("tax_type", models.CharField(blank=True, max_length=20)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "tax_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("logo_url", models.URLField(blank=True)),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B60C5",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Must be a valid hex color code"
                            )
                        ],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#EC633D",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Must be a valid hex color code"
                            )
                        ],
                    ),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("TRIAL", "14-day Trial"),
                            ("STARTER", "Starter (10 rooms)"),
                            ("PROFESSIONAL", "Professional (50 rooms)"),
                            ("ENTERPRISE", "Enterprise (unlimited)"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("max_rooms", models.IntegerField(default=5)),
                ("max_staff", models.IntegerField(default=3)),
                ("max_monthly_bookings", models.IntegerField(default=50)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("ANNUAL", "Annual")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("allow_custom_domain", models.BooleanField(default=False)),
                ("allow_api_access", models.BooleanField(default=False)),
                ("allow_white_label", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("ESEWA", "eSewa"),
                            ("KHALTI", "Khalti"),
                            ("FONEPAY", "Fonepay"),
                            ("RAZORPAY", "Razorpay"),
                            ("PAYTM", "Paytm"),
                            ("PHONEPE", "PhonePe"),
                            ("BKASH", "bKash"),
                            ("NAGAD", "Nagad"),
                            ("IPAY", "iPay"),
                            ("STRIPE", "Stripe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("merchant_id", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("api_endpoint", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("test_mode", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_configs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Gateway Config",
                "verbose_name_plural": "Payment Gateway Configs",
                "db_table": "payment_gateway_configs",
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "gateway")},
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Hotel Owner"),
                            ("MANAGER", "Manager"),
                            ("FRONT_DESK", "Front Desk"),
                            ("HOUSEKEEPING", "Housekeeping"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Membership",
                "verbose_name_plural": "Tenant Memberships",
                "db_table": "tenant_memberships",
                "ordering": ["-created_at"],
                "unique_together": {("user", "tenant")},
            },
        ),
    ]
