# Generated by Django 6.1.1 on 2026-10-01 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_subscriptionpayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_APPROVAL", "Pending Admin Approval"),
                    ("TRIAL", "Trial Period"),
                    ("ACTIVE", "Active Subscription"),
                    ("SUSPENDED", "Suspended - Payment Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("ARCHIVED", "Archived - Deleted"),
                    ("REJECTED", "Rejected by Admin"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StaffInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Hotel Owner"),
                            ("MANAGER", "Manager"),
                            ("FRONT_DESK", "Front Desk"),
                            ("HOUSEKEEPING", "Housekeeping"),
                        ],
                        default="FRONT_DESK",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_accepted", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_staff_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_invitations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Invitation",
                "verbose_name_plural": "Staff Invitations",
                "db_table": "staff_invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantVerificationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            (
                                "BUSINESS_REGISTRATION",
                                "Business Registration / Incorporation",
                            ),
                            ("PAN_VAT_CERTIFICATE", "PAN / VAT Registration"),
                            ("HOTEL_LICENSE", "Hotel / Tourism Board License"),
                            ("OWNER_GOVT_ID", "Owner Government ID / Passport"),
                            ("PROPERTY_PROOF", "Property Ownership or Lease Agreement"),
                            ("OTHER", "Other Supporting Document"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="tenant_verifications/"
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_documents",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Verification Document",
                "verbose_name_plural": "Tenant Verification Documents",
                "db_table": "tenant_verification_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
